/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nicro' at '19.10.17 09:15' with Gradle 2.14.1
 *
 * @author nicro, @date 19.10.17 09:15
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
